### ISSUE TITLE
Self Checklist

### ISSUE THREAD

**Issue by AidanLau10** [AidanLau10/aidan_2025#5]
| Skill         | Mastered (Y/N) | Rank (1-4) | Ratio | Notes |
  |---------------|----------------|------------|-------|-------|
  | Attendance    | [Y]            | 4          | 1.0   |       |
  | Work Habits   | [Y]            | 4          | 1.0   |       |
  | Behavior      | [Y]            | 4         | 1.0   |       |
  | Timeliness    | [Y]            | 4          | 1.0   |       |
  | Tech Sense    | [Y]            | 4          | 1.0   |   |
  | Tech Talk     | [Y]            | 4         | 1.0   |       |
  | Tech Growth   | [Y]            | 4          | 1.0   |       |
  | Advocacy      | [Y]            | 4          | 1.0   |       |
  | Comm & Collab | [Y]            | 4          | 1.0   |       |
  | Integrity     | [Y]            | 4          | 1.0   |       |
  | Organized     | [Y]            | 4          | 1.0   |       |
  | **Total**     |       11         |            |       | 0.0   |
  | **Average**   |                |            |       | 0.0   |
  
  
  ## Student Skills Checklist
  
  - [x] **Laptop Verification or Cloud Workspace**
    - Rank: 0
    - Notes: verification by Linux commands notebook
  
  - [x] **VSCode**
    - Rank: 0
    - Notes: live change code, commit, make, run localhost, test, debug
  
  - [x] **Show VSCode GitLens**
    - Rank: 0
    - Notes: verify commits, show change, comments, reset to commit, run on old commit
  
  - [x] **GitHub Cloud Repo**
    - Rank: 0
    - Notes: live push change, verify id, review profile
  
  - [x] **GitHub Pages Actions**
    - Rank: 0
    - Notes: review runs and verify runtime, receive demo
  
  - [x] **Hacks Tools & Equipment Play**
    - Rank: 0
    - Notes:
  
  - [x] **Hacks GitHub Pages Playground**
    - Rank: 0
    - Notes:
  
  - [x] **Hacks SASS Basics**
    - Rank: 0
    - Notes:
  
  - [x] **Hacks Jupyter Notebook**
    - Rank: 0
    - Notes:
  
  - [x] **Pair Programming**
    - Rank: 0
    - Notes: tangibles that show co-operative work
